### ISSUE TITLE
Please create Minor release for composer

### ISSUE THREAD

**Issue by possi** [magespecialist/MSP_Common#2]
Tag v1.0.0 doesn't contain a composer.json, so the modul can only installed as dev stability ("dev-master").
If you could please create a Tag v1.0.1, this could be found by composer as stable.
Tanks in advanced.

Also you may create a pull request to add all your composer projects to packages.firegento.com: https://github.com/magento-hackathon/composer-repository

**Comment by slackerzz** [comment]
tagged v1.0.1
